name: enviroment_data

on:
 push:

jobs:
 github-pages:
  runs-on: ubuntu-latest
  environment: github-pages
  env:
   APIKey: ${{ secrets.TOKEN }}
  steps:
   - name: Read env
     run: echo "env ${{secrets.TOKEN}}"
   - name: Overwrite file
     uses: "DamianReeves/write-file-action@master"
     with:
      path: ./config.js
      write-mode: overwrite
      contents: |
       const TOKEN = "https://script.google.com/macros/s/AKfycbzfwkUv1rmt7jaIBEjZu5D_EJS9Nj775SRld_aOk_uYQJdDyYIs76eDXKqTx2Dlv1QyfA/exec"; export default TOKEN;
