name: enviroment_test

on:
 workflow_dispatch

jobs:
 github-pages:
  runs-on: ubuntu-latest
  environment: github-pages
  env:
   APIKey: ${{ secrets.TOKEN }}
  steps:
   - name: Read env
     run: echo "env ${{secrets.TOKEN}}"
   - name: creating import
     run: cd js && echo -e "const TOKEN = 'api-token';\n\nexport default TOKEN;" > config.js
