name: enviroment_data

on:
 push:

jobs:
 github-pages:
  runs-on: ubuntu-latest
  environment: github-pages
  env:
   APIKey: ${{ secrets.TOKEN }}
  steps:
   - name: Read env
     run: echo "env ${{secrets.TOKEN}}"
   - name: creating import
     run: echo -e "const TOKEN = ${{secrets.TOKEN}};\n\nexport default TOKEN;" > config.js
